Name:           ros-kinetic-freenect-launch
Version:        0.4.1
Release:        0%{?dist}
Summary:        ROS freenect_launch package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/freenect_launch
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-freenect-camera
Requires:       ros-kinetic-image-proc
Requires:       ros-kinetic-nodelet
Requires:       ros-kinetic-rgbd-launch
Requires:       ros-kinetic-tf
BuildRequires:  ros-kinetic-catkin

%description
Launch files for freenect_camera to produce rectified, registered or disparity
images. Also produce point clouds and registered point clouds. Based on the
openni_launch package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon May 23 2016 Jack O'Quin <jack.oquin@gmail.com> - 0.4.1-0
- Autogenerated by Bloom

